IF EXISTS ( SELECT TABLE_NAME FROM INFORMATION_SCHEMA.VIEWS WHERE TABLE_NAME = 'V_THAISAN_STUDENT_GROUP_HISTORY') 
	DROP VIEW V_THAISAN_STUDENT_GROUP_HISTORY;
GO

CREATE VIEW V_THAISAN_STUDENT_GROUP_HISTORY AS
SELECT
	dbo.STUDENT.STUDENT_ID,
	dbo.STUDENT.STUDENT_NAME,
	dbo.STUDENT.STUDENT_NAME_IN_KHMER,
	dbo.STUDENT.SEX,
	dbo.STUDENT.DATE_OF_BIRTH,
	dbo.STUDENT.PHONE,
	dbo.STUDENT_GROUP.TERM_NO,
	dbo.[GROUP].GROUP_NAME,
	dbo.SCHOOL.SCHOOL_NAME,
	dbo.SCHOOL.SCHOOL_NAME_IN_KHMER,
	dbo.FIELD.FIELD_NAME,
	dbo.FIELD.FIELD_NAME_IN_KHMER,
	dbo.STAGE.STAGE_NO,
	dbo.PROMOTION.PROMOTION_NO,
	dbo.DEGREE.DEGREE,
	dbo.DEGREE.DEGREE_IN_KHMER
FROM
	dbo.STUDENT
INNER JOIN dbo.STUDENT_GROUP ON dbo.STUDENT.STUDENT_ID = dbo.STUDENT_GROUP.STUDENT_ID
INNER JOIN dbo.[GROUP] ON dbo.STUDENT_GROUP.GROUP_ID = dbo.[GROUP].GROUP_ID
INNER JOIN dbo.STAGE ON dbo.[GROUP].STAGE_ID = dbo.STAGE.STAGE_ID
INNER JOIN dbo.PROMOTION ON dbo.STAGE.PROMOTION_ID = dbo.PROMOTION.PROMOTION_ID
INNER JOIN dbo.FIELD ON dbo.[GROUP].FIELD_ID = dbo.FIELD.FIELD_ID
INNER JOIN dbo.SCHOOL ON dbo.FIELD.SCHOOL_ID = dbo.SCHOOL.SCHOOL_ID
INNER JOIN dbo.DEGREE ON dbo.PROMOTION.DEGREE_ID = dbo.DEGREE.DEGREE_ID
AND dbo.FIELD.DEGREE_ID = dbo.DEGREE.DEGREE_ID

IF EXISTS ( SELECT TABLE_NAME FROM INFORMATION_SCHEMA.VIEWS WHERE TABLE_NAME = 'V_THAISAN_STUDENT_PAYMENT') 
	DROP VIEW V_THAISAN_STUDENT_GROUP_HISTORY;
GO

CREATE VIEW V_THAISAN_STUDENT_PAYMENT AS
SELECT
	dbo.STUDENT.STUDENT_ID,
	dbo.STUDENT.STUDENT_NAME,
	dbo.STUDENT.STUDENT_NAME_IN_KHMER,
	dbo.STUDENT.SEX,
	dbo.STUDENT.DATE_OF_BIRTH,
	dbo.STUDENT.PHONE,
	dbo.PAYMENT.INVOICE_NO,
	dbo.PAYMENT.INVOICE_DATE,
	dbo.PAYMENT.TERM_NO,
	dbo.PAYMENT.PAID,
	dbo.PAYMENT.DEPOSIT,
	dbo.PAYMENT.NOTE
FROM
	dbo.STUDENT
INNER JOIN dbo.PAYMENT ON dbo.STUDENT.STUDENT_ID = dbo.PAYMENT.STUDENT_ID;